controllers/CustomersController.php
<?php

namespace app\controllers;

use Yii;
use app\models\customer\Customer;
use app\models\customer\CustomerRecord;
use app\models\customer\Phone;
use app\models\customer\PhoneRecord;

use yii\data\ArrayDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;

class CustomersController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'actions' => ['add'],
                        'roles' => ['admin', 'manager'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['index', 'query', 'results'],
                        'roles' => ['admin', 'manager', 'user'],
                        'allow' => true,
                    ],
                ],

            ],
        ];
    }

    public function actionIndex()
    {
        $customers = CustomerRecord::find()->limit(20)->all();
        $records = $this->wrapIntoDataProvider($customers);

        return $this->render('index', \compact('records'));
    }

    public function actionAdd()
    {
        $customer = new CustomerRecord();
        $phone = new PhoneRecord();

        if ($this->load($customer, $phone, $_POST)) {
            $this->store($this->makeCustomer($customer, $phone));

            return $this->redirect('/customers');
        }

        // statefull magic: both $customer and $phone will be validated at this point
        return $this->render('add', \compact('customer', 'phone'));
    }

    public function actionQuery()
    {
        return $this->render('query');
    }

    public function actionResults()
    {
        $records = $this->findRecordsByQuery();

        return $this->render('results', \compact('records'));
    }

    private function store(Customer $customer)
    {
        $customer_record = new CustomerRecord();
        $customer_record->name = $customer->name;
        // $customer_record->birth_date = $customer->birth_date->format('Y-m-d');
        $customer_record->birth_date
            = Yii::$app->formatter->asDate($customer->birth_date, 'php:Y-m-d');
        $customer_record->notes = $customer->notes;

        $customer_record->save();

        foreach ($customer->phones as $phone) {
            $phone_record = new PhoneRecord();
            $phone_record->number = $phone->number;
            $phone_record->customer_id = $customer_record->id;
            $phone_record->save();
        }
    }

    private function makeCustomer(
        CustomerRecord $customer_record,
        PhoneRecord $phone_record
    ) {
        $name = $customer_record->name;
        $birth_date = new \DateTime($customer_record->birth_date);

        $customer = new Customer($name, $birth_date);
        $customer->notes = $customer_record->notes;
        $customer->phones[] = new Phone($phone_record->number);

        return $customer;
    }

    private function load(
        CustomerRecord $customer,
        PhoneRecord $phone,
        array $post
    ) {
        return $customer->load($post)
                and $phone->load($post)
                and $customer->validate()
                and $phone->validate(['number']);
    }

    private function findRecordsByQuery()
    {
        $number = Yii::$app->request->get('phone_number');
        $records = $this->getRecordsByPhoneNumber($number);
        $dataProvider = $this->wrapIntoDataProvider($records);

        return $dataProvider;
    }

    private function wrapIntoDataProvider($data)
    {
        return new ArrayDataProvider(
            [
                'allModels' => $data,
                'pagination' => false,
            ]
        );
    }

    private function getRecordsByPhoneNumber($number)
    {
        $phone_record = PhoneRecord::findOne(['number' => $number]);

        if (!$phone_record) {
            return [];
        }

        $customer_record = CustomerRecord::findOne($phone_record->customer_id);

        if (!$customer_record) {
            return [];
        }

        return [
            $this->makeCustomer($customer_record, $phone_record),
        ];
    }
}

controllers/ServicesController.php
<?php

namespace app\controllers;

use Yii;
use app\models\service\ServiceRecord;
use app\models\service\ServiceSearchModel;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * ServicesController implements the CRUD actions for ServiceRecord model.
 */
class ServicesController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'actions' => [],
                        'roles' => ['admin', 'manager'],
                        'allow' => true,
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all ServiceRecord models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ServiceSearchModel();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single ServiceRecord model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new ServiceRecord model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new ServiceRecord();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing ServiceRecord model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing ServiceRecord model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the ServiceRecord model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return ServiceRecord the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = ServiceRecord::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use \yii\web\Controller;
use app\models\user\LoginForm;
use yii\filters\AccessControl;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['login', 'logout', 'docs'],
                'rules' => [
                    [
                        'actions' => ['login'],
                        'roles' => ['?'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'docs'],
                        'roles' => ['@'],
                        'allow' => true,
                    ],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionDocs()
    {
        return $this->render('docindex.md');
    }

    /**
     * Login user
     * @return View login view
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();

        if ($model->load(Yii::$app->request->post())
            && $model->login()) {
            return $this->goBack();
        }

        return $this->render('login', \compact('model'));
    }

    /**
     * Logout user
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

views/layouts/main.php
<?php

/**
 * @var string $content
 * @var $this yii\web\View
 */
use yii\helpers\Html;
use app\common\widgets\Alert;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;

// \yii\bootstrap\BootstrapAsset::register($this);
// \yii\web\YiiAsset::register($this);
app\assets\AppAsset::register($this);
?>
<?php $this->beginPage(); ?>
    <!DOCTYPE html>
    <html lang="<?php echo Yii::$app->language; ?>">
    <head>
        <meta charset="<?php echo Yii::$app->charset; ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title><?php echo Html::encode($this->title); ?></title>
        <?php $this->head(); ?>
        <?php echo Html::csrfMetaTags(); ?>
    </head>
    <body>
        <?php $this->beginBody(); ?>
        <div class="wrap">
            <?php
                NavBar::begin([
                    'brandLabel' => Yii::$app->name,
                    'brandUrl' => Yii::$app->homeUrl,
                    'options' => [
                        'class' => 'navbar-default navbar-fixed-top',
                    ],
                ]);
                $menuItems = [
                    ['label' => 'Customers', 'url' => ['/customers/index']],
                    ['label' => 'Customer add', 'url' => ['/customers/add']],
                    ['label' => 'Customers query', 'url' => ['/customers/query']],
                    ['label' => 'Services', 'url' => ['/services/index']],
                    ['label' => 'Documentation', 'url' => ['/site/docs']],
                    ['label' => 'Gii', 'url' => ['/gii']],
                ];
                /*
                if (Yii::$app->user->isGuest) {
                    $menuItems[] = ['label' => 'Signup', 'url' => ['/site/signup']];
                    $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']];
                } else {
                    $menuItems[] = '<li>'
                    . Html::beginForm(['/site/logout'], 'post')
                    . Html::submitButton(
                        'Logout (' . Yii::$app->user->identity->username . ')',
                        ['class' => 'btn btn-link logout']
                    )
                    . Html::endForm()
                        . '</li>';
                }
                 */
                echo Nav::widget([
                    'options' => ['class' => 'navbar-nav navbar-right'],
                    'items' => $menuItems,
                ]);
                NavBar::end();
            ?>
            <div class="container">
                <?php echo Breadcrumbs::widget([
                    'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                ]); ?>
                <?php echo Alert::widget(); ?>
                <?php echo $content; ?>
            </div>
        </div>

        <footer class="footer">
            <div class="container">
                <div class="pull-left">
                    &copy; <?php echo 'Kalnynsh D ' . date('Y'); ?>
                </div>
                <div class="pull-right">
                    <?php echo Yii::powered(); ?>
                </div>
            </div>
        </footer>

        <?php $this->endBody(); ?>
    </body>
    </html>
<?php $this->endPage(); ?>