controllers/CustomersController.php
<?php

namespace app\controllers;

use Yii;
use app\models\customer\Customer;
use app\models\customer\CustomerRecord;
use app\models\customer\Phone;
use app\models\customer\PhoneRecord;

use yii\data\ArrayDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;

class CustomersController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'actions' => ['add'],
                        'roles' => ['admin', 'manager'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['index', 'query', 'results'],
                        'roles' => ['admin', 'manager', 'user'],
                        'allow' => true,
                    ],
                ],

            ],
        ];
    }

    public function actionIndex()
    {
        $customers = CustomerRecord::find()->limit(20)->all();
        $records = $this->wrapIntoDataProvider($customers);

        return $this->render('index', \compact('records'));
    }

    public function actionAdd()
    {
        $customer = new CustomerRecord();
        $phone = new PhoneRecord();

        if ($this->load($customer, $phone, $_POST)) {
            $this->store($this->makeCustomer($customer, $phone));

            return $this->redirect('/customers');
        }

        // statefull magic: both $customer and $phone will be validated at this point
        return $this->render('add', \compact('customer', 'phone'));
    }

    public function actionQuery()
    {
        return $this->render('query');
    }

    public function actionResults()
    {
        $records = $this->findRecordsByQuery();

        return $this->render('results', \compact('records'));
    }

    private function store(Customer $customer)
    {
        $customer_record = new CustomerRecord();
        $customer_record->name = $customer->name;
        // $customer_record->birth_date = $customer->birth_date->format('Y-m-d');
        $customer_record->birth_date
            = Yii::$app->formatter->asDate($customer->birth_date, 'php:Y-m-d');
        $customer_record->notes = $customer->notes;

        $customer_record->save();

        foreach ($customer->phones as $phone) {
            $phone_record = new PhoneRecord();
            $phone_record->number = $phone->number;
            $phone_record->customer_id = $customer_record->id;
            $phone_record->save();
        }
    }

    private function makeCustomer(
        CustomerRecord $customer_record,
        PhoneRecord $phone_record
    ) {
        $name = $customer_record->name;
        $birth_date = new \DateTime($customer_record->birth_date);

        $customer = new Customer($name, $birth_date);
        $customer->notes = $customer_record->notes;
        $customer->phones[] = new Phone($phone_record->number);

        return $customer;
    }

    private function load(
        CustomerRecord $customer,
        PhoneRecord $phone,
        array $post
    ) {
        return $customer->load($post)
                and $phone->load($post)
                and $customer->validate()
                and $phone->validate(['number']);
    }

    private function findRecordsByQuery()
    {
        $number = Yii::$app->request->get('phone_number');
        $records = $this->getRecordsByPhoneNumber($number);
        $dataProvider = $this->wrapIntoDataProvider($records);

        return $dataProvider;
    }

    private function wrapIntoDataProvider($data)
    {
        return new ArrayDataProvider(
            [
                'allModels' => $data,
                'pagination' => false,
            ]
        );
    }

    private function getRecordsByPhoneNumber($number)
    {
        $phone_record = PhoneRecord::findOne(['number' => $number]);

        if (!$phone_record) {
            return [];
        }

        $customer_record = CustomerRecord::findOne($phone_record->customer_id);

        if (!$customer_record) {
            return [];
        }

        return [
            $this->makeCustomer($customer_record, $phone_record),
        ];
    }
}

views/customers/_customer.php
<?php

/**
 * @var Customer $model
 */
use app\models\customer\Customer;

echo \yii\widgets\DetailView::widget(
    [
        'model' => $model,
        'attributes' => [
            ['attribute' => 'name'],
            [
                'attribute' => 'birth_date',
                'value' =>
                    (gettype($model->birth_date) === 'string')
                        ? $model->birth_date
                        : $model->birth_date->format('Y-m-d'),
            ],
            'notes:text',
            ['label' => 'phone_number', 'attribute' => 'phones.0.number'],
        ]
    ]
);

views/customers/add.php
<?php
use app\models\customer\CustomerRecord;
use app\models\customer\PhoneRecord;
use yii\web\View;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * Add Customer UI
 *
 * @var View $this
 * @var CustomerRecord $customer
 * @var PhoneRecord $phone
 */

$this->title = 'Customer add';
$this->params['breadcrumbs'][] = $this->title;

$form = ActiveForm::begin([
    'id' => 'add-customer-form',
]);

echo $form->errorSummary(([$customer, $phone]));
echo $form->field($customer, 'name');
echo $form->field($customer, 'birth_date');
echo $form->field($customer, 'notes');

echo $form->field($phone, 'number');

echo Html::submitButton('Submit', ['class' => 'btn btn-primary']);
ActiveForm::end();

views/customers/index.php
<?php

/**
 * @var  $this yii\web\View
 * @var \yii\data\BaseDataProvider $records
 */

$this->title = 'Customers';
$this->params['breadcrumbs'][] = $this->title;

echo \yii\widgets\ListView::widget(
    [
        'options' => [
            'class' => 'list-view',
            'id' => 'customers_index'
        ],
        'itemView' => '_customer',
        'dataProvider' => $records
    ]
);

views/customers/query.php
<?php

use \yii\helpers\Html;

$this->title = 'Customers query';
$this->params['breadcrumbs'][] = $this->title;

echo Html::beginForm(['/customers/results'], 'get');

echo Html::label('Phone number to search:', 'phone_number');
echo Html::textInput('phone_number');
echo Html::submitButton('Search');

echo Html::endForm();

views/customers/results.php
<?php

/**
 * @var \yii\data\BaseDataProvider $records
 */
echo \yii\widgets\ListView::widget(
    [
        'options' => [
            'class' => 'list-view',
            'id' => 'search_results'
        ],
        'itemView' => '_customer',
        'dataProvider' => $records
    ]
);